import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillInstagram, AiFillGithub} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from '../public/design.png';
import code from '../public/code.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from "react";


export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Colin Cargile Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">Developed By</h1>
            <ul className="flex items=center">
              <li >
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="Technical Resume Colin2.pdf" download="Technical Resume Colin2.pdf">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-burtons font-md md:text-6xl">
              Colin M. Cargile
            </h2>
            <h3 className="text-2xl font-burtons py-2 md:text-3xl dark:text-white">
              Developer and Photographer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl dark:text-white">
              Passionate and solutions driven full stack web developer with a web development certificate from Columbia University Engineering School and a Java full stack development certificate from Southern Methodist University. Utilizing the skills of analysis, collaboration, communication and team problem solving to create projects from ideation to execution. Ability to work in a fast paced and diverse team environment developing solutions and exceeding expectations.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <div className="cursor-pointer">
              <a href="https://www.linkedin.com/in/colin-cargile-71b289166">
              <AiFillLinkedin />
              </a>
            </div>
            <div className="cursor-pointer">
              <a href="https://github.com/GundamMosi10">
              <AiFillGithub />
              </a>
            </div>
            <div className="cursor-pointer">
              <a href="https://www.instagram.com/colinmosi/">
              <AiFillInstagram />
              </a>
            </div>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
        </section>
        <section>
          <div>
              <h3 className="text-center text-2xl font-burtons py-8 md:text-3xl dark:text-white">
                Services I offer
              </h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 flex-1">
                <Image src={code} width={100} height={100}/>
                <h3 className="text-lg font-burtons font-medium pt-8 pb-2 dark:text-white">
                  Web Development
                </h3>
                <p className="py-2 dark:text-white">I’m excited to become a part of a quality-driven team to develop and create impactful user experiences by continuing to learn throughout each project we tackle as a team. </p>
                <h4 className="py-4 text-teal-600">Technologies</h4>
                <p className="text-gray-800 py-1 dark:text-white">Java</p>
                <p className="text-gray-800 py-1 dark:text-white">SpringBoot</p>
                <p className="text-gray-800 py-1 dark:text-white">JavaScript</p>
                <p className="text-gray-800 py-1 dark:text-white">React</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 basis-1/3 flex-1">
                <Image src={design} width={100} height={100}/>
                <h3 className="text-lg font-burtons font-medium pt-8 pb-2 dark:text-white">
                  Photography
                </h3>
                <p className="py-2 dark:text-white">Creating elegant photographs suited for your needs</p>
                <h4 className="py-4 text-teal-600">Photography Tools I use</h4>
                <p className="text-gray-800 py-1 dark:text-white">Photoshop</p>
                <p className="text-gray-800 py-1 dark:text-white">Illustrator</p>
                <p className="text-gray-800 py-1 dark:text-white">Adobe Lightroom</p>
              </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl font-burtons py-1 dark:text-white">
              Portfolio
            </h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
